### PR TITLE
fixed generics in typednamedsendablechooser

### PR DESCRIPTION
**Pull request by leijurv**
like the other generic pull, this one fixes all the eclipse warnings for the file, etc

### CODE REVIEW

**Comment by c0d3rman** [comment]
@leijurv Could you document how to enable these warnings for future people reviewing the standard library?

**Comment by leijurv** [comment]
I mean... the warnings are no longer being shown because they are fixed... To replace the errors, undo this change

**Comment by c0d3rman** [comment]
No, I mean when they are investigating other files, how to see all Eclipse warnings (the same ones you used to find this issue). Or are all warnings shown by default in the Problems pane?

**Comment by leijurv** [comment]
Oh, I have FindBugs and PMD installed. But the generic type-warnings I was talking about are from javac / eclipse warnings.

**Pull request merged**
