### PR TITLE
rethrow exceptions instead of just printing stack trace and continuing

### PR DESCRIPTION
**Pull request by leijurv**

### CODE REVIEW

**Comment by leijurv** [comment]
Why wouldn't this be correctable?

**Comment by leijurv** [comment]
Throwing exceptions when an error occurs is a good idea even when the code cannot recover from said error (such as the "this should never happen" error)

**Comment by carturn** [comment]
Is there a way to catch an error from a static initializer? If so, then this would be fine supposing that we did so.

**Comment by carturn** [comment]
In the case of logging, it is more important that the rest of the robot work than logging work. The worst-case scenario would be code failure for the duration of a match, and while this is unlikely, it should be avoided. I think in the case of the robot, if an error can not be recovered from, the subsystem the error occurred within should be disabled, but the rest of the code should simply ignore the error.

**Comment by leijurv** [comment]
Ah, I see.

**Pull request closed without merging**
