### PR TITLE
use reference to constructing class

### PR DESCRIPTION
**Pull request by leijurv**

### CODE REVIEW

**Comment by c0d3rman** [comment]
I wanted to get some other people's feedback on whether this is a good change - @ajnadel @HowardStark could one of you take a look?

**Comment by leijurv** [comment]
17 days ago: I wanted to get some other people's feedback on whether this is a good change - @ajnadel @HowardStark could one of you take a look? @c0d3rman

**Comment by tylkahn** [comment]
5 days later...

**Comment by leijurv** [comment]
@ajnadel @HowardStark @c0d3rman

**Comment by c0d3rman** [comment]
Go ahead and test.

**Pull request merged**
