### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by carturn**
Just a bunch of javadocs.

### CODE REVIEW

**Comment by carturn** [comment]
This has not been tested. It will this afternoon.

**Comment by tobbrau** [comment]
it worked

**Comment by tobbrau** [comment]
it drove

**Comment by oshlern** [comment]
The Robot drove around. YAY

**Comment by tobbrau** [comment]
i saw

**Comment by tylkahn** [comment]
It did. I saw it with my very own eyes.

**Comment by oshlern** [comment]
Comments don't break things

**Comment by tobbrau** [comment]
hi

**Comment by ajnadel** [comment]
I can vouch that this conversation happened on GitHub. 






On Wed, Jan 27, 2016 at 4:11 PM -0800, "oshlern" <notifications@github.com> wrote:












Comments don't break things

**Comment by ajnadel** [comment]
mad props for verbing javadoc

**Pull request merged**
