### PR TITLE
Superbutton enhancement

### PR DESCRIPTION
**Pull request by c0d3rman**
Improved SuperButton.

### CODE REVIEW

**Comment by carturn** [comment]
:+1: once tested.

**Comment by carturn** [comment]
I maintain :+1: once tested. I added some stuff to use CustomButtons in CustomXbox. Also, they should be called CustomButtons, not SuperButtons, to avoid confusion with java super keyword. We have been using Custom as the standard elsewhere in standard.

**Comment by carturn** [comment]
cancelWhenReleased and onlyWhileHeld work, but onlyWhileReleased starts running after you release the button and stops running when you press it again. I am not sure if this is the intended behavior.

**Comment by c0d3rman** [comment]
onlyWhileReleased should have the exact opposite effect of
onlyWhilePressed. So what you are describing is correct, except it should
run the command before the first press of the button.

**Comment by carturn** [comment]
@c0d3rman I do not think that is possible because the command (or CustomButton) would have to detect when the robot is enabled and start the command then.

**Comment by carturn** [comment]
:+1:

**Comment by carturn** [comment]
"Improved Javadocing" also made the commands start automatically.

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
