### PR TITLE
kitten level as enum instead of class with public constructor

### PR DESCRIPTION
**Pull request by leijurv**

### CODE REVIEW

**Comment by leijurv** [comment]
The backwards compatibility (in which referencing the field LogKitten.LEVEL_whatever still works) should help

**Comment by leijurv** [comment]
One thing to be careful of: I had to remove compareTo because Enum.compareTo is final and can't be overridden. Comparisons should be the same, as the enum values are listed in the correct order, but this is a coincidence at the moment.

**Comment by c0d3rman** [comment]
This looks like an excellent addition. @leijurv, perhaps add a comment indicating the importance of declaring KittenLevels in order? Also, I would appreciate if you could update the title/description of this PR to better reflect what the changes are and why you made them (for posterity).

**Comment by leijurv** [comment]
@c0d3rman thoughts on severity as the ordinal of the enum?

**Comment by c0d3rman** [comment]
@leijurv I think it's very clever! I would add a clarifying comment, though.

**Comment by leijurv** [comment]
It does have `// Defined in decreasing order of severity. Enum.compareTo uses the definition order to compare enum values.`

**Comment by c0d3rman** [comment]
Yes, which is why I approved the changes as is - I just thought it'd be a nice addition. Thanks for adding it! I think this is 100% ready for testing.

**Comment by HowardStark** [comment]
Tested. Looks good.

**Pull request merged**
