### PR TITLE
Synchronized logkitten logging methods

### PR DESCRIPTION
**Pull request by c0d3rman**
This PR synchronizes all of the LogKitten logging methods.
This mirrors the changes on `skynet-sockets`.
@HowardStark please devise a way to test this and report back.

### CODE REVIEW

**Comment by c0d3rman** [comment]
Does not seem to break anything.

**Comment by c0d3rman** [comment]
As @leijurv pointed out, this may cause issues because these methods are called many times a second (especially `d`) from different threads and write to files and hence this may create a backlog.
`logMessage` is notably not synchronized. @HowardStark – am I misunderstanding this?

**Comment by leijurv** [comment]
All the methods that call logMessage don't need to be synchronized, it suffices to just have logMessage be synchronized. Methods that set fields to the argument don't need to be synchronized. It suffices to set a boolean as volatile, as that will automatically synchronize accesses.

**Comment by leijurv** [comment]
+1

**Comment by leijurv** [comment]
+1

**Comment by leijurv** [comment]
+1

**Comment by leijurv** [comment]
+1

**Pull request merged**
