### PR TITLE
Inner classes should be static wherever possible

### PR DESCRIPTION
**Pull request by leijurv**

### CODE REVIEW

**Comment by leijurv** [comment]
I'm not sure if there's a precedent for accessing static inner classes, but I would lean towards accessing it as it is now. Non-static inner classes are bad practice (e.g. because they maintain a reference to their enclosing instance which hurts gc)

**Comment by c0d3rman** [comment]
Does it pass the formatter?
Also, I agree with the idea of static inner classes, I'm just trying to decide on a convention on how to access them.

**Comment by leijurv** [comment]
closing in favor of #129

**Comment by c0d3rman** [comment]
Please make sure to delete branches on closed PRs @leijurv

**Pull request closed without merging**
