### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by carturn**
Merging some documentation.

### CODE REVIEW

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
There are some issues with line breaks and indentation. Please !fix.

**Comment by c0d3rman** [comment]
!fix

**Comment by c0d3rman** [comment]
!resolve

**Comment by c0d3rman** [comment]
!fix

**Comment by carturn** [comment]
Still tested.

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
