### PR TITLE
Fixed motors for 2/11 update. This is urgent.

### PR DESCRIPTION
**Pull request by carturn**
This adds stopMotor.
Please merge ASAP, new plugin will not build without this.

### CODE REVIEW

**Comment by c0d3rman** [comment]
Build failed. Travis's version of WPILIB needs update?

**Comment by c0d3rman** [comment]
Submitted issue https://github.com/chopshop-166/wpilib-mirror/issues/1

**Comment by carturn** [comment]
Made our own version of the wpilib-mirror the default. We can not depend on another team for every pull request.

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
