### PR TITLE
Twitchtimv

### PR DESCRIPTION
**Pull request by leijurv**

### CODE REVIEW

**Comment by leijurv** [comment]
@c0d3rman

**Comment by leijurv** [comment]
the reason why it's in sensor motor is that PIDController.get has to return *some* number, not like it can return null (hmm). The issue is that it doesn't know what to return at all on the first tick, so it's returning 0 or similar, *that's what causing the twitch*. Whatever's calling PIDController I suppose would need to detect the first iteration and ignore the result, that's why I made justReset public and implemented it in sensor motor

**Comment by leijurv** [comment]
Maybe PIDController should return an Optional<Double> or a @Nullable Double

**Comment by c0d3rman** [comment]
That sounds like a good idea - perhaps add a second `getNullable` method (or a better name) so if you're just making a quick implementation you can use `get` but implementations in the standard library (like in SensorMotor) can use `getNullable`? That sounds great – if you think it's worth adding while we get the thread implementation working go for it. (If not it may get incorporated into that implementation if needed)

**Pull request closed without merging**
