### PR TITLE
New slope control

### PR DESCRIPTION
**Pull request by carturn**
This turns slope control into a class seperate from motor, which fixes issues with needing (but not being able to have) diamond inheritance.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/RoboticsTeam4904/standard/pull/27" target="_blank">ReviewNinja

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Comment by carturn** [comment]
:+1: After changes last night, this needs to be retested.

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
