### PR TITLE
Fixed chassis set. Now has a timeout and finishes.

### PR DESCRIPTION
**Pull request by carturn**

### CODE REVIEW

**Comment by c0d3rman** [comment]
Care to elaborate on why this is needed?

**Comment by carturn** [comment]
I want ChassisSet to do something that will not result in robot damage.

**Comment by c0d3rman** [comment]
Has this been tested?

**Comment by carturn** [comment]
No. It does not have the tested label.

**Comment by c0d3rman** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
