### PR TITLE
Added more base Commands

### PR DESCRIPTION
**Pull request by c0d3rman**
Added more base commands:

- Cancel cancels a given command on initialize
- Idle does nothing but requires the given subsystem (intended to be used as a default command, which must require the subsystem)
- RunFor runs the given command for a given duration and then cancels it
- RunIf uses anonymous interfaces (optionally made a LOT cleaner by the Java 8 double colon; see comments in code) to run the given command only if the given function(s) returns true.
- RunUnless does the opposite of RunIf

### CODE REVIEW

**Comment by carturn** [comment]
addSequential needs to be in the constructor

**Comment by carturn** [comment]
Also, I maintain that we should try to avoid Java 8 syntax.

**Comment by c0d3rman** [comment]
The documentation on the RunIf and RunUnless commands gives a Java 7- alternative, but the Java 8 syntax is cleaner and better.
Also, does it have to be? If I move it to the constructor it will evaluate the check at construct-time, not initialize-time, so I'd have to skip the CommandGroup structure and manually spawn the command (which would have other downsides, like not using CommandGroup's requirement handling.)

**Comment by carturn** [comment]
The code will literally not run unless addSequential is in the constructor. The command will not initialize until the CommandGroup initializes though.

**Comment by carturn** [comment]
I like all of these except RunIf and RunUnless. I also feel like RunFor should be done by extending whatever class you are running for some time.

**Comment by c0d3rman** [comment]
OK, this is problematic - we can't do the check at initialize time if we addSequential at construct-time.
However, RunIf is going to be important for CommandGroups like Shoot that need to call things like flywheel.isSpunUp and hood.isUp at initialize time. I don't want a RockToShootIfSpunUpAndHoodUp command.

**Comment by carturn** [comment]
I think RunIf and RunUnless are just going to have to be more complicated commands.

**Comment by carturn** [comment]
Shoot could be a commandGroup with sequential hood up, then spin up, then rock to shoot.

**Comment by carturn** [comment]
Also, the existence of a BooleanInterface bothers me.

**Comment by c0d3rman** [comment]
But that's not what the trigger does. In our control scheme the trigger rocks to the shoot position iff the hood is up and the flywheel is spun up. So Shoot cannot do those things, it can only check for them.

**Comment by carturn** [comment]
Fine, so Shoot has to take in the hood and the flywheel and do checks on them.

**Comment by carturn** [comment]
I think that is probably the best way to do that. I agree that it would be better to have a generic version, but I think it is more complicated than it is worth.

**Comment by carturn** [comment]
Also, when you end a commandGroup, it automatically cancels all subcommands.

**Comment by c0d3rman** [comment]
Shoot already takes them in, but cannot run checks on them - that is the problem I was addressing when I created these commands. Shoot is a CommandGroup and so must `addSequential` at construct-time. It can't check the flywheel and hood at runtime.

**Comment by carturn** [comment]
Why is shoot a command group?

**Comment by carturn** [comment]
Should not it just be RockToShoot?

**Comment by c0d3rman** [comment]
It has to check whether it can shoot (and possibly send some signals to the DS for the color-coding).

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Comment by carturn** [comment]
Idle, Cancel, and RunFor works.

**Comment by carturn** [comment]
RunIf, RunUnless, and RunIfElse work.

**Comment by carturn** [comment]
:+1:

**Comment by c0d3rman** [comment]
:+1:

**Pull request merged**
